# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# Brewery.create!(name: "New Park Brewing", address: "485 New Park Ave", city:"West Hartford", state:"CT", zip: "06110")
# Brewery.create!(name: "Two Roads Brewing Company", address: "1700 Stratford Ave", city:"Stratford", state:"CT", zip: "06615")
# Brewery.create!(name: "Stony Creek Brewery", address: "5 Indian Neck Ave", city:"Branford", state:"CT", zip: "06405")



#CT BREWERY SEEDS

Brewery.create!(name:"2nd Bridge Brewing Company", address: "642 Hilliard St", city: "Manchester", state: "CT", zip: "06042")
Brewery.create!(name:"30 Mile Brewing Co.", address: "39 Ragged Rock Rd", city: "Old Saybrook", state: "CT", zip: "06475")
Brewery.create!(name:"Alvarium Beer Co.", address: "365 John Downey Dr b", city: "New Britain", state: "CT", zip: "06051")
Brewery.create!(name:"Armada Brewing", address: "250 Bradley St", city: "East Haven", state: "CT", zip: "06512")
Brewery.create!(name:"Aspetuck Brew Lab", address: "3389 Fairfield Ave", city: "Bridgeport", state: "CT", zip: "06605")
Brewery.create!(name:"Athletic Brewing Co.", address: "350 Long Beach Blvd", city: "Stratford", state: "CT", zip: "06615")
Brewery.create!(name:"Back East Brewing", address: "1296 Blue Hills Ave", city: "Bloomfield", state: "CT", zip: "06002")
Brewery.create!(name:"Bad Dream Brewing", address: "116 Danbury Rd Unit #3", city: "New Milford", state: "CT", zip: "06776")
Brewery.create!(name:"Bad Sons Beer Co.", address: "251 Roosevelt Dr", city: "Derby", state: "CT", zip: "06418")
# Brewery.create!(name:"BAR", address: "254 Crown St", city: "New Haven", state: "CT", zip: "06511")
# Brewery.create!(name:"Barley Head Brewery", address: "12 Water St Unit 1A", city: "Mystic", state: "CT", zip: "06355")
# Brewery.create!(name:"Beer'd Brewing Co.", address: "22 Bayview Ave  Unit 15", city: "Stonington", state: "CT", zip: "06378")
# Brewery.create!(name:"Black Hog Brewing", address: "115 Hurley Rd #9A", city: "Oxford", state: "CT", zip: "06478")
# Brewery.create!(name:"Black Pond Brews", address: "21 Furnace St", city: "Danielson", state: "CT", zip: "06239")
# Brewery.create!(name:"Brass Works Brewing Co.", address: "2056 Thomaston Ave", city: "Waterbury", state: "CT", zip: "06704")
# Brewery.create!(name:"Breakaway Brew Haus", address: "5 Steeles Crossing Rd", city: "Bolton", state: "CT", zip: "06043")
# Brewery.create!(name:"Brewery Legitimus", address: "283 Main St B3", city: "New Hartford", state: "CT", zip: "06057")
# Brewery.create!(name:"Brewport", address: "387 Warren St", city: "Bridgeport", state: "CT", zip: "06604")
# Brewery.create!(name:"Broad Brook Brewing", address: "915 South St", city: "Suffield", state: "CT", zip: "06078")
# Brewery.create!(name:"Broken Symmetry Gastro Brewery", address: "5 Depot Pl", city: "Bethel", state: "CT", zip: "06801")
# Brewery.create!(name:"Cambridge House Brew Pub", address: "357 Salmon Brook St", city: "Granby", state: "CT", zip: "06035")
# Brewery.create!(name:"Center Street Brewing Co.", address: "25 Wallace St", city: "Wallingford", state: "CT", zip: "06492")
# Brewery.create!(name:"Charter Oak Brewing Co.", address: "39 Shelter Rock Rd", city: "Danbury", state: "CT", zip: "06810")
# Brewery.create!(name:"City Steam Brewery", address: "942 Main St", city: "Hartford", state: "CT", zip: "06103")
# Brewery.create!(name:"Cliffside Brewing", address: "16B Center St", city: "Wallingford", state: "CT", zip: "06492")
# Brewery.create!(name:"Cold Creek Tavern", address: "175 West Rd", city: "Ellington", state: "CT", zip: "06029")
# Brewery.create!(name:"Connecticut Valley Brewing Co.", address: "765 Sullivan Ave", city: "South Windsor", state: "CT", zip: "06074")
# Brewery.create!(name:"Cottrell Brewing Co.", address: "100 Mechanic St #22", city: "Pawcatuck", state: "CT", zip: "06379")
# Brewery.create!(name:"Counterweight Brewing Co.", address: "23 Raccio Park Rd", city: "Hamden", state: "CT", zip: "06514")
# Brewery.create!(name:"DuVig Brewing Co.", address: "59 School Ground Rd  Suite #10", city: "Branford", state: "CT", zip: "06405")
# Brewery.create!(name:"East Rock Brewing Co.", address: "285 Nicoll St", city: "New Haven", state: "CT", zip: "06511")
# Brewery.create!(name:"Epicure Brewing", address: "40 Franklin St", city: "Norwich", state: "CT", zip: "06360")
# Brewery.create!(name:"Erector Brewing Collective", address: "687 State St", city: "New Haven", state: "CT", zip: "06511")
# Brewery.create!(name:"Fairfield Craft Ales", address: "724A Honeyspot Rd", city: "Stratford", state: "CT", zip: "06615")
# Brewery.create!(name:"Fat Orange Cat Brew Co.", address: "47 Tartia Rd", city: "East Hampton", state: "CT", zip: "06424")
# Brewery.create!(name:"Firefly Hollow Brewing Co.", address: "139 Center St", city: "Bristol", state: "CT", zip: "06010")
# Brewery.create!(name:"Five Churches Brewing", address: "193 Arch St", city: "New Britain", state: "CT", zip: "06051")
# Brewery.create!(name:"Forest City Brewing", address: "180 Johnson St", city: "Middletown", state: "CT", zip: "06457")
# Brewery.create!(name:"Fox Farm Brewery", address: "62 Music Vale Rd", city: "Salem", state: "CT", zip: "06420")
# Brewery.create!(name:"Front Porch Brewing", address: "226 N. Plains Industrial Rd  Unit #4", city: "Wallingford", state: "CT", zip: "06492")
# Brewery.create!(name:"Great Falls Brewing Company", address: "1 Railroad Plaza", city: "North Canaan", state: "CT", zip: "06018")
# Brewery.create!(name:"Half Full Brewery", address: "43 Homestead Ave", city: "Stamford", state: "CT", zip: "06902")
# Brewery.create!(name:"Hanging Hills Brewing Co.", address: "150 Ledyard St", city: "Hartford", state: "CT", zip: "06114")
# Brewery.create!(name:"Hoax Brewing", address: "250 Bradley St", city: "East Haven", state: "CT", zip: "06512")
# Brewery.create!(name:"Hog River Brewing Co.", address: "1429 Park St", city: "Hartford", state: "CT", zip: "06106")
# Brewery.create!(name:"Hop Culture Farms & Brewing Co.", address: "144 Cato Corner Rd", city: "Colchester", state: "CT", zip: "06415")
# Brewery.create!(name:"Hops on the Hill Farm Brewery", address: "275 Dug Rd", city: "South Glastonbury", state: "CT", zip: "06073")
# Brewery.create!(name:"Housatonic River Brewing", address: "30 Kent Rd", city: "New Milford", state: "CT", zip: "06776")
# Brewery.create!(name:"Hull's Brewing Co.", address: "250 Bradley St", city: "East Haven", state: "CT", zip: "06512")
# Brewery.create!(name:"Iron Brewing Co.", address: "136 Washington St", city: "Norwalk", state: "CT", zip: "06854")
# Brewery.create!(name:"Kent Falls Brewing Co.", address: "33 Camps Rd", city: "Kent", state: "CT", zip: "06757")
# Brewery.create!(name:"Kinsmen Brewing Co.", address: "409 Canal St", city: "Milldale", state: "CT", zip: "06467")
# Brewery.create!(name:"Labyrinth Brewing Co.", address: "148 Forest St Unit #24", city: "Manchester", state: "CT", zip: "06040")
# Brewery.create!(name:"Lasting Brass Brewing Co.", address: "1864 Watertown Ave", city: "Oakville", state: "CT", zip: "06779")
# Brewery.create!(name:"Little House Brewing", address: "16 Main St", city: "Chester", state: "CT", zip: "06412")
# Brewery.create!(name:"Little Red Barn Brewers", address: "32 Lake St", city: "Winsted", state: "CT", zip: "06098")
# Brewery.create!(name:"Lock City Brewing Co.", address: "54 Research Dr", city: "Stamford", state: "CT", zip: "06906")
# Brewery.create!(name:"Milford Point Brewing", address: "230 Woodmont Rd Unit 29B", city: "Milford", state: "CT", zip: "06460")
# Brewery.create!(name:"New England Brewing Co.", address: "175 Amity Rd", city: "Woodbridge", state: "CT", zip: "06525")
# Brewery.create!(name:"New Park Brewing", address: "485 New Park Ave", city: "West Hartford", state: "CT", zip: "06110")
# Brewery.create!(name:"Niantic Public House and Brewery", address: "243 Main St", city: "Niantic", state: "CT", zip: "06357")
# Brewery.create!(name:"Nighthawk Brewing", address: "250 Bradley St", city: "East Haven", state: "CT", zip: "06512")
# Brewery.create!(name:"Noble Jay Brewing Co.", address: "11 Freedom Way", city: "Niantic", state: "CT", zip: "06357")
# Brewery.create!(name:"No Worries Brewing Co.", address: "2520 State St", city: "Hamden", state: "CT", zip: "06517")
# Brewery.create!(name:"Nod Hill Brewery", address: "137 Ethan Allen Way", city: "Ridgefield", state: "CT", zip: "06877")
# Brewery.create!(name:"Norbrook Farm Brewery", address: "204 Stillman Hill Rd", city: "Colebrook", state: "CT", zip: "06021")
# Brewery.create!(name:"OEC Brewing", address: "7 Fox Hollow Rd", city: "Oxford", state: "CT", zip: "06478")
# Brewery.create!(name:"Outer Light Brewing Co.", address: "266 Bridge St", city: "Groton", state: "CT", zip: "06340")
# Brewery.create!(name:"Overshores Brewing Co.", address: "250 Bradley St,", city: "East Haven", state: "CT", zip: "06512")
# Brewery.create!(name:"Powder Hollow Brewery", address: "504 Hazard Ave", city: "Enfield", state: "CT", zip: "06082")
# Brewery.create!(name:"Problem Solved Brewing Co.", address: "2 North Rd", city: "East Windsor", state: "CT", zip: "06088")
# Brewery.create!(name:"Redding Beer Co.", address: "7 Main St", city: "Redding", state: "CT", zip: "06896")
# Brewery.create!(name:"Relic Brewing Co.", address: "123 Whiting St", city: "Plainville", state: "CT", zip: "06062")
# Brewery.create!(name:"Reverie Brewing Co.", address: "57B Church Hill Rd", city: "Newtown", state: "CT", zip: "06470")
# Brewery.create!(name:"Rhythm Brewing Co.", address: "32 Barnett St", city: "New Haven", state: "CT", zip: "06515")
# Brewery.create!(name:"Shebeen Brewing Co.", address: "1 Wolcott Rd", city: "Wolcott", state: "CT", zip: "06716")
# Brewery.create!(name:"Skygazer Brewing Co.", address: "36 Triano Dr", city: "Southington", state: "CT", zip: "06489")
# Brewery.create!(name:"Skulls Brew House", address: "1 Wolcott Rd", city: "Wolcott", state: "CT", zip: "06716")
# Brewery.create!(name:"Soundview Brewing Co.", address: "88 Hartford Ave", city: "Old Lyme", state: "CT", zip: "06371")
# Brewery.create!(name:"Steady Habit Brewing Co.", address: "95 Bridge Rd", city: "Haddam", state: "CT", zip: "06438")
# Brewery.create!(name:"Still Hill Brewery", address: "1275 Cromwell Ave Building C Unit 9", city: "Rocky Hill", state: "CT", zip: "06067")
# Brewery.create!(name:"Stony Creek Brewery", address: "5 Indian Neck Ave", city: "Branford", state: "CT", zip: "06405")
# Brewery.create!(name:"Stony Creek Brewery at Foxwoods Casino", address: "350 Trolley Line Blvd", city: "Mashantucket", state: "CT", zip: "06338")
# Brewery.create!(name:"Stranger Tides Brewing", address: "199 Old Hartford Rd", city: "Colchester", state: "CT", zip: "06415")
# Brewery.create!(name:"Stubborn Beauty Brewing Co.", address: "180 Johnson St", city: "Middletown", state: "CT", zip: "06457")
# Brewery.create!(name:"Taylor Brooke Brewery", address: "848 Route 171", city: "Woodstock", state: "CT", zip: "06281")
# Brewery.create!(name:"The Beeracks", address: "250 Bradley St", city: "East Haven", state: "CT", zip: "06512")
# Brewery.create!(name:"The Brewery at Maple View Farm", address: "192 Salmon Brook St", city: "Granby", state: "CT", zip: "06035")
# Brewery.create!(name:"The Crossings Restaurant & Brew Pub", address: "45 Main St", city: "Putnam", state: "CT", zip: "06260")
# Brewery.create!(name:"The Stack Brewery, BBQ & Biergarten", address: "470 James St", city: "New Haven", state: "CT", zip: "06513")
# Brewery.create!(name:"These Guys Brewing Co.", address: "78 Franklin St", city: "Norwich", state: "CT", zip: "06360")
# Brewery.create!(name:"Thimble Island Brewing Co.", address: "16 Business Park Dr", city: "Branford", state: "CT", zip: "06405")
# Brewery.create!(name:"Thomas Hooker Brewing Co.", address: "16 Tobey Rd", city: "Bloomfield", state: "CT", zip: "06002")
# Brewery.create!(name:"Thomas Hooker Brewery at Colt", address: "140 Huyshope Ave", city: "Hartford", state: "CT", zip: "06106")
# Brewery.create!(name:"Tox Brewing Company", address: "635 Broad St", city: "New London", state: "CT", zip: "06320")
# Brewery.create!(name:"Tribus Beer Co.", address: "100 Raton Rd", city: "Milford", state: "CT", zip: "06461")
# Brewery.create!(name:"Two Roads Brewing Co.", address: "1700 Stratford Ave", city: "Stratford", state: "CT", zip: "06615")
# Brewery.create!(name:"Two Roads Brewing Co. Area Two Experimental Brewing", address: "1526 Stratford Ave", city: "Stratford", state: "CT", zip: "06615")
# Brewery.create!(name:"Veracious Brewing Co.", address: "246 Main St", city: "Monroe", state: "CT", zip: "06468")
# Brewery.create!(name:"Willimantic Brewing Co.", address: "967 Main St", city: "Willimantic", state: "CT", zip: "06226")
# Brewery.create!(name:"Witchdoctor Brewing Co.", address: "168 Center St", city: "Southington", state: "CT", zip: "06489")
# Brewery.create!(name:"Woodbury Brewing Co.", address: "738 Main St. S", city: "Woodbury", state: "CT", zip: "06798")

#USER SEEDS
User.create!(first_name: "Rachel" , last_name: "Kopp", email: "rlksquam@gmail.com", password: "password")
User.create!(first_name: "Meg" , last_name: "DeJong", email: "mmdNYC@gmail.com", password: "password")


#CT BREWERY REVIEW SEEDS
Review.create!(user_id: 1, brewery_id: 1, rating: 5, title: "Great place to hang out and try new beers", body: "I had such a great time here with my friends last weekend! The beer was great, the staff was very nice, and the space has such a cool vibe to it. The Cool Runner IPA is awesome and would totally have again!")
Review.create!(user_id: 2, brewery_id: 1, rating: 5, title: "Awesome for family and friends", body: "This place was great for hanging out with family and friends. I went here for my friend's birthday with our young kids and the outdoor space was great for our little party. Would come back again!")
